settings:
  title: 'Status Page'
  url: 'https://ryansprogramming.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Main Site # unique identifier
    name: ryansprogramming.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://ryansprogramming.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Support
    name: ryansprogramming.com/support
    description: 'Main support site for RP'
    url: 'https://ryansprogramming.com/support'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true


